# Generated by Django 4.2.7 on 2025-08-20 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône FontAwesome", max_length=50, null=True, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Catégorie d'emploi",
                'verbose_name_plural': "Catégories d'emploi",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la compétence')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Compétence populaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.jobcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('requirements', models.TextField(verbose_name='Exigences du poste')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsabilités')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Avantages')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Télétravail possible')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('interim', 'Intérim')], default='cdi', max_length=20, verbose_name='Type de contrat')),
                ('experience_required', models.CharField(choices=[('0-1', '0-1 an'), ('1-3', '1-3 ans'), ('3-5', '3-5 ans'), ('5-10', '5-10 ans'), ('10+', '10+ ans')], default='1-3', max_length=10, verbose_name='Expérience requise')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('skills_required', models.TextField(help_text='Séparez les compétences par des virgules', verbose_name='Compétences requises')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Fermé'), ('paused', 'En pause')], default='draft', max_length=20, verbose_name='Statut')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Date limite de candidature')),
                ('max_applications', models.PositiveIntegerField(default=100, verbose_name='Nombre maximum de candidatures')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobcategory', verbose_name='Catégorie')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Publié par')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
    ]
